<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Summy\Core'                => __DIR__ . '/Core.php',
    'Summy\Filter\En\Stemmer'   => __DIR__ . '/Filter/En/Stemmer.php',
    'Summy\Filter\En\StopWords' => __DIR__ . '/Filter/En/StopWords.php',
    'Summy\Filter\En\Text'      => __DIR__ . '/Filter/En/Text.php',
    'Summy\Filter\Gr\Stemmer'   => __DIR__ . '/Filter/Gr/Stemmer.php',
    'Summy\Filter\Gr\StopWords' => __DIR__ . '/Filter/Gr/StopWords.php',
    'Summy\Filter\Gr\Text'      => __DIR__ . '/Filter/Gr/Text.php',
    'Summy\Filter\StopWords'    => __DIR__ . '/Filter/StopWords.php',
    'Summy\Filter\WordLength'   => __DIR__ . '/Filter/WordLength.php',
    'Summy\Score\Position'      => __DIR__ . '/Score/Position.php',
    'Summy\Score\Term'          => __DIR__ . '/Score/Term.php',
);